# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- uat

pool:
  vmImage: 'windows-latest'

    
steps:
- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'Orch Conn'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

- task: UiPathTest@2
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'Orch Conn'
    testProjectPath: '$(Build.SourcesDirectory)'
    environment: 'Development Environment'
    folderName: 'Frankie_Classic'
    testReportDestination: '$(Build.ArtifactStagingDirectory)\TestsOutput'


- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'Orch Conn'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Frankie_Classic'
    environments: 'Development Environment'

- script: echo UiPath CI/CD steps done!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
